### ISSUE TITLE
可不可以抓包获取题目呢

### ISSUE THREAD

**Issue by Sowevo** [se4/cddh#1]
可不可以抓包获取题目呢

**Comment by se4** [comment]
显然可以，而且没有验证
`http://htpmsg.jiecaojingxuan.com/msg/current`

**Comment by se4** [comment]
已经根据一些基础的权重算法，结合rest接口做完了一版，等待今天中午验证。

**Comment by Samuel0807** [comment]
现在抓包获取的题目是有错误的

**Comment by Kingson** [comment]
刚才尝试，显示：
// 20180109171755
// http://htpmsg.jiecaojingxuan.com/msg/current

{
  "code": 0,
  "msg": "no data"
}

**Comment by se4** [comment]
@Kingson 只有有题目的时候才会出现结果，这个只要瞟一眼代码就能看到了，我是担心被淘宝卖家滥用所以不写说明，给大家带来不便了！

**Comment by fanOfJava** [comment]
现在抓包的接口是不是挂了
